### ISSUE TITLE
Mid transfer & spendable coins UX

### ISSUE THREAD

**Issue by linnutee** [commerceblock/mercury-wallet#204]
For "Mid-transfer" and Spendable coins (ie. Sent to another Statecoin wallet) would recommend using a clearer name "Send Pending" or something in lines of that. On row components, this status has the "Copy Transfer Code" link next to it, which should also trigger a feedback  tooltip, "Transfer Code was copied to Clipboard. Send it to the Receiver of the Transaction". Also the same blurb is available in the coin modal. 

As these coins can still be used, I would recommend the following: 
- Automatically hide the "Mid Transfer" coins from any other interactions (swaps, send, withdraw). 
- Display a Cancel button within the coin details modal (accessed from Overview). 
- Upon clicking Cancel, user is then prompted with a confirmation and a short explainer text what will occur. 

<img width="1668" alt="Screenshot 2021-04-07 at 18 27 02" src="https://user-images.githubusercontent.com/17774057/113893937-2e41fb80-97d0-11eb-8e74-357a16e2f90a.png">

**Comment by 86667** [comment]
I think it makes sense to have coins IN_TRANSFER (transfer_sender performed) considered spent and accessed by selecting to view “transferred coins” tab in Coins list (similar to how withdraw coins are viewed [here](https://github.com/commerceblock/mercury-wallet/issues/217). 

Otherwise, if we consider IN_TRANSFER coins as not yet spent, we must have some form of polling the server to find out when transfer_receiver has been performed so that the coins can be marked SPENT .

**Comment by 86667** [comment]
https://github.com/commerceblock/mercury-wallet/pull/236
